import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common'; import { DatabaseService } from '../database/database.service';
type D={companyId:string;customerNumber:string;customerName:string;driverNumber:string;firstName:string;lastName:string;driverCode:string;active?:boolean}; type A={sub:string;email:string;role:string;companyId?:string};
@Injectable() export class DriversService{constructor(private readonly db:DatabaseService){}
 list(companyId:string,actor:{sub:string;role:string}){return this.db.query(`SELECT d.id,d.company_id AS "companyId",c.code AS company,d.full_name AS "fullName",d.customer_number AS "customerNumber",d.customer_name AS "customerName",d.driver_number AS "driverNumber",d.first_name AS "firstName",d.last_name AS "lastName",d.driver_code AS "driverCode",d.active,
  coalesce(jsonb_agg(jsonb_build_object('id',v.id,'registration',v.registration_display)) FILTER(WHERE v.id IS NOT NULL),'[]') AS vehicles
  FROM driver d JOIN company c ON c.id=d.company_id LEFT JOIN vehicle v ON v.driver_id=d.id AND v.deleted_at IS NULL WHERE d.deleted_at IS NULL
  AND ($1='' OR d.company_id=$1::uuid) AND ($2::boolean=false OR EXISTS(SELECT 1 FROM fuel_card fc WHERE fc.company_id=d.company_id AND fc.responsible_user_id=$3 AND fc.deleted_at IS NULL))
  GROUP BY d.id,c.code ORDER BY c.code,d.driver_number NULLS LAST,d.full_name`,[companyId,actor.role==='NAJIB_ASSIGNER',actor.sub]);}
 async create(dto:D,a:A){this.assertCompanyScope(dto.companyId,a);const values=this.values(dto);try{const [r]=await this.db.query(`INSERT INTO driver(company_id,full_name,customer_number,customer_name,driver_number,first_name,last_name,driver_code,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[dto.companyId,...values,dto.active??true]);await this.audit(a,'CREATE',r.id,r);return r;}catch(error){this.handleUnique(error);}}
 async update(id:string,dto:D,a:A){const [current]=await this.db.query<{company_id:string}>('SELECT company_id FROM driver WHERE id=$1 AND deleted_at IS NULL',[id]);if(!current)throw new NotFoundException('Chauffeur introuvable');this.assertCompanyScope(current.company_id,a);this.assertCompanyScope(dto.companyId,a);const values=this.values(dto);try{const [r]=await this.db.query(`UPDATE driver SET company_id=$2,full_name=$3,customer_number=$4,customer_name=$5,driver_number=$6,first_name=$7,last_name=$8,driver_code=$9,active=$10,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING *`,[id,dto.companyId,...values,dto.active??true]);await this.audit(a,'UPDATE',id,r);return r;}catch(error){this.handleUnique(error);}}
 async remove(id:string,a:A){const [current]=await this.db.query<{company_id:string}>('SELECT company_id FROM driver WHERE id=$1 AND deleted_at IS NULL',[id]);if(!current)throw new NotFoundException('Chauffeur introuvable');this.assertCompanyScope(current.company_id,a);const [r]=await this.db.query(`UPDATE driver SET deleted_at=now(),active=false WHERE id=$1 AND deleted_at IS NULL RETURNING id`,[id]);await this.audit(a,'SOFT_DELETE',id,{deleted:true});return {success:true};}
 private assertCompanyScope(companyId:string,a:A){if(a.role==='NAJIB_ASSIGNER'&&a.companyId!==companyId)throw new BadRequestException('Vous pouvez gérer uniquement les chauffeurs de votre société');}
 private values(dto:D){const firstName=dto.firstName.trim();const lastName=dto.lastName.trim().toUpperCase();return [`${firstName} ${lastName}`,dto.customerNumber.trim(),dto.customerName.trim().toUpperCase(),dto.driverNumber.trim().padStart(4,'0'),firstName,lastName,dto.driverCode.trim().padStart(4,'0')];}
 private handleUnique(error:unknown):never{if((error as {code?:string}).code==='23505')throw new BadRequestException('Le numéro ou le code chauffeur existe déjà pour cette société');throw error;}
 private audit(a:A,action:string,id:string,v:unknown){return this.db.query(`INSERT INTO audit_log(actor,action,entity_type,entity_id,new_values) VALUES($1,$2,'driver',$3,$4)`,[a.email,action,id,v]);}}
