import { BadRequestException,Injectable } from '@nestjs/common'; import { DatabaseService } from '../database/database.service';
@Injectable() export class FuelPricesService{constructor(private readonly db:DatabaseService){}
 list(companyId:string){return this.db.query(`SELECT fp.id,fp.company_id AS "companyId",c.code AS company,fp.product,fp.old_price AS "oldPrice",fp.new_price AS "newPrice",fp.variation_percent AS "variationPercent",fp.effective_date AS "effectiveDate",u.display_name AS "createdBy",fp.created_at AS "createdAt" FROM fuel_price fp JOIN company c ON c.id=fp.company_id LEFT JOIN app_user u ON u.id=fp.created_by WHERE ($1='' OR fp.company_id=$1::uuid) ORDER BY fp.effective_date DESC,fp.created_at DESC`,[companyId]);}
 async create(dto:{companyId:string;product:string;newPrice:number;effectiveDate?:string},actor:{sub:string;email:string}){return this.db.transaction(async client=>{
  const previous=await client.query(`SELECT new_price FROM fuel_price WHERE company_id=$1 AND lower(product)=lower($2) ORDER BY effective_date DESC,created_at DESC LIMIT 1`,[dto.companyId,dto.product.trim()]);
  const oldPrice=Number(previous.rows[0]?.new_price??dto.newPrice); if(oldPrice<=0)throw new BadRequestException('Ancien prix invalide'); const variation=100*(dto.newPrice-oldPrice)/oldPrice;
  const created=await client.query(`INSERT INTO fuel_price(company_id,product,old_price,new_price,variation_percent,effective_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[dto.companyId,dto.product.trim(),oldPrice,dto.newPrice,variation,dto.effectiveDate??new Date().toISOString().slice(0,10),actor.sub]);
  if(Math.abs(variation)>0){await client.query(`UPDATE fuel_card SET monthly_limit=round(monthly_limit*(1+$2/100),3) WHERE company_id=$1 AND deleted_at IS NULL AND monthly_limit>0`,[dto.companyId,variation]);
   await client.query(`INSERT INTO notification(user_id,title,message,target_view,entity_type,entity_id) SELECT id,'Plafonds ajustés au prix carburant',$2,'cards','fuel_price',$3 FROM app_user WHERE active AND (company_id=$1 OR role IN('ZIN_FINANCE','DIRECTION_GENERAL','SUPER_ADMIN'))`,[dto.companyId,`Le prix ${dto.product} varie de ${variation.toFixed(2)} %. Les plafonds de la société ont été ajustés dans la même proportion.`,created.rows[0].id]);}
  await client.query(`INSERT INTO audit_log(actor,action,entity_type,entity_id,new_values) VALUES($1,'FUEL_PRICE_CHANGE','fuel_price',$2,$3)`,[actor.email,created.rows[0].id,{oldPrice,newPrice:dto.newPrice,variation}]);return {id:created.rows[0].id,oldPrice,newPrice:dto.newPrice,variationPercent:variation,limitsUpdated:Math.abs(variation)>0};});}}
